Repository MDSplus/mdsplus, pull requests merged in 2024-04, with the labels that each got.

#2735 Fix: When activate debug trace, now compiles without error.
  _include/mdsmsg.h
  mdstcpip/mdsipshr/MdsValue.c
  servershr/ServerSendMessage.c
Labels: bug, US Priority, branch/alpha, core

#2740 Fix: reduce open files due to dispatcher
  servershr/Client.h
  servershr/ServerDispatchPhase.c
  servershr/ServerQAction.c
  servershr/ServerSendMessage.c
  servershr/servershrp.h
Labels: bug, US Priority, tool/tcl

#2732 Docs: Improve documentation for getSegment* python wrappers
  python/MDSplus/tree.py
Labels: api/python

#2747 Fix: Update JAVASOURCE to 8 to support JDK 17
  java/mdsobjects/Makefile.am
  java/mdsplus/Makefile.am
Labels: bug, api/java

#2748 Fix: multiple string escape warnings thrown by python 12
  pydevices/MitDevices/dt100.py
  pydevices/RfxDevices/CYGNET4K.py
  pydevices/RfxDevices/FAKECAMERA.py
  pydevices/RfxDevices/PLFE.py
Labels: bug, api/python, devices

#2749 Build: Resolve linker error after updating the windows builder to Fedora 39
  mdsdcl/Makefile.in
  mdsobjects/cpp/mdsdatastreams.cpp
  mdsobjects/cpp/testing/MdsTdiTest.cpp
  mdsobjects/cpp/testing/MdsTreeNodeTest.cpp
  mdsshr/Makefile.in
  tdishr/TdiGetDbi.c
  tdishr/TdiGetNci.c
Labels: build, os/windows

#2752 Fix: mdsip now sends proper auth status back to the client
  mdstcpip/mdsipshr/Connections.c
Labels: bug, US Priority, tool/mdsip, branch/alpha

#2754 Fix: mdstcl's `show current` no longer segfaults when no tree paths defined
  treeshr/TreeGetSetShotId.c
Labels: bug, US Priority, tool/tcl, core

#2753 Fix: Add Debian 12 and Ubuntu 24.04 and support GCC 12+
  Jenkinsfile
  configure.ac
  deploy/os/debian12-64.opts
  deploy/os/ubuntu24.opts
  m4/m4_ax_c_flags.m4
  mdsdcl/cmdExecute.c
  python/MDSplus/compound.py.in
Labels: build
