Repository MDSplus/mdsplus, pull requests merged in 2024-02, with the labels that each got.

#2701 Build: Sign packages with Jenkins, upload Windows installers to GitHub
  Jenkinsfile
  deploy/packaging/windows/create_installer.sh
  deploy/platform/debian/debian_docker_build.sh
  deploy/platform/redhat/redhat_docker_build.sh
Labels: build

#2702 Build: Actually publish to the real directory
  Jenkinsfile
Labels: build

#2703 Fix: corrected typo that caused MdsPut2() to clear all flags
  mdslib/MdsLib.c
Labels: bug, US Priority, core

#2705 Fix: Release versioning was always 1 behind
  Jenkinsfile
  deploy/build.sh
  deploy/git_revision.sh
Labels: build

#2707 Fix: Restructure the Jenkinsfile to better support versioning
  Jenkinsfile
Labels: build

#2706 Fix: User provided fix to prevent rare segfault on device deletion
  treeshr/TreeDeleteNode.c
Labels: bug, core

#2711 Build: configure PYTHONPATH for IDL test harness
  Jenkinsfile
Labels: feature, test, US Priority, api/idl

#2656 Build: enhance IDL test harness by adding write tests and more read tests
  idl/testing/run_tests.py
Labels: US Priority, api/idl, branch/alpha

#2712 Build: parameterize the "write" tree for MATLAB tests
  matlab/testing/run_tests.py
Labels: feature, test, US Priority, api/matlab

#2714 Fix: mdsip no longer accepts connections from unauthorized users
  mdstcpip/mdsipshr/Connections.c
Labels: bug, core

#2722 Build: correctly format expected output for a MATLAB test
  matlab/testing/run_tests.py
Labels: build, test
