Repository MDSplus/mdsplus, pull requests merged in 2024-01, with the labels that each got.

#2672 Initial Jenkinsfile
  Jenkinsfile
  README.md
  deploy/git_revision.sh
  deploy/platform/bootstrap/bootstrap_build.sh
  deploy/platform/platform_build.sh
Labels: build

#2675 Build: Add cleanWs() after build to the Jenkinsfile
  Jenkinsfile
Labels: build

#2676 Fix: tdic uses correct env var and path to launch tcl
  tdic/tdic.c
Labels: tool/tdi, branch/alpha

#2677 Build: Fix build.sh to test the ExitCode from docker
  deploy/platform/platform_build.sh
Labels: build

#2678 Fix test event port, collect and import test results into Jenkins
  Jenkinsfile
  deploy/tap-to-junit.py
Labels: build

#2680 Work on isolating each build/test in their own network
  Jenkinsfile
  deploy/build.sh
  deploy/platform/platform_build.sh
Labels: build

#2661 Gm fix apd
  deploy/packaging/debian/kernel.noarch
  deploy/packaging/debian/matlab.noarch
  deploy/packaging/redhat/kernel.noarch
  deploy/packaging/redhat/matlab.noarch
  include/mdsobjects.h
  java/mdsobjects/src/main/java/MDSplus/Apd.java
  java/mdsobjects/src/main/java/MDSplus/Connection.java
  java/mdsobjects/src/main/java/MDSplus/Data.java
  java/mdsobjects/src/main/java/MDSplus/List.java
  javamds/mdsobjects.c
  matlab/mdsput.m
  matlab/private/javaFromMatlab.m
  matlab/private/javaFromMatlabCell.m
  matlab/private/javaFromMatlabStruct.m
  matlab/private/javaToMatlab.m
  matlab/private/javaToMatlabCell.m
  matlab/private/javaToMatlabStruct.m
  mdsobjects/cpp/mdsipobjects.cpp
  python/MDSplus/connection.py
  tdi/treeshr/TreePutDeserialized.fun
  tdishr/TdiEvaluate.c
  tdishr/TdiGetData.c
  tditest/testing/test-tab.ans
Labels: bug

#2679 Work on adding the IDL tests to the Jenkinsfile
  Jenkinsfile
  idl/testing/run_tests.py
Labels: build, api/idl

#2685 Restructure the Jenkinsfile
  Jenkinsfile
Labels: build

#2686 Begin work on publishing
  Jenkinsfile
  deploy/create_github_release.py
  deploy/get_new_version.py
  deploy/platform/debian/debian_docker_build.sh
  deploy/platform/platform_build.sh
  deploy/platform/redhat/redhat_docker_build.sh
Labels: build

#2692 Build: Treat unprefixed commits as "Fix:"
  deploy/get_new_version.py
Labels: build

#2694 Build: Give the tgz files absolute paths
  Jenkinsfile
Labels: build

#2699 Add darren as an Admin so he can build PRs
  Jenkinsfile
Labels: build
