Repository MDSplus/mdsplus, pull requests merged in 2024-05, with the labels that each got.

#2744 Fix: Improve error messaging when calling Setup Device in jTraverser
  java/jtraverser/src/main/java/mds/jtraverser/Node.java
Labels: tool/jTraverser

#2756 Build: Fix off-by-one versions produced by Jenkins
  Jenkinsfile
  deploy/platform/bootstrap/bootstrap_build.sh
Labels: bug, build

#2757 Build: Increase default test timeout to 1h
  mdsobjects/cpp/testing/MdsConnectionTest.cpp
  mdsobjects/cpp/testing/MdsTdiTest.cpp
  mdsobjects/cpp/testing/MdsTreeNodeTest.cpp
  mdsobjects/cpp/testing/MdsTreeSegments.cpp
  mdsobjects/cpp/testing/MdsTreeTest.cpp
  testing/testing.h
Labels: build

#2758 Build: Fix 'HEAD' in `show version` and tag error
  Jenkinsfile
  deploy/platform/bootstrap/bootstrap_build.sh
Labels: build

#2760 Fix: mdstcl show version tag and links
  _include/_mdsversion.h.in
  mdsdcl/mdsdcl_show_version.c
Labels: bug, build, tool/tcl

#2446 Feature: CompileTree will exit with non-zero status code for error messages.
  java/jtraverser/src/main/java/mds/jtraverser/CompileTree.java
Labels: feature

#2764 Fix: Python release version tag
  python/MDSplus/_version.py.in
Labels: bug, build, api/python

#2767 Feature: Add "Date:" to show version output
  _include/_mdsversion.h.in
  mdsdcl/mdsdcl_show_version.c
Labels: feature, build, tool/tcl

#2769 Fix: remove abort flag from RfxDevices DIO2 initialization
  tdi/RfxDevices/DIO2__init.fun
Labels: US Priority, devices, branch/alpha

#2770 Fix: Missing repo metadata signing
  Jenkinsfile
Labels: bug, build

#2774 Feature: jScope improvements
  java/jscope/src/main/java/mds/jscope/jScopeMultiWave.java
  java/jscope/src/main/java/mds/provider/AsciiDataProvider.java
  java/jscope/src/main/java/mds/provider/MdsDataProvider.java
  java/jscope/src/main/java/mds/provider/TwuDataProvider.java
  java/jscope/src/main/java/mds/provider/UniversalDataProvider.java
  java/jscope/src/main/java/mds/wave/DataProvider.java
  java/jscope/src/main/java/mds/wave/DataServerItem.java
  java/jscope/src/main/java/mds/wave/Signal.java
  java/jscope/src/main/java/mds/wave/WaveInterface.java
  java/mdsobjects/src/main/java/mds/connection/Descriptor.java
  mdsmisc/ScopeUtilities.c
Labels: feature, tool/jScope

#2775 Docs: Update GitHub Bug Report Template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, do-not-build

#2773 Fix: sign the RPM package repo's metadata
  deploy/platform/redhat/redhat_docker_build.sh
Labels: bug, branch/stable, packaging, branch/alpha

#2776 Build: Lower test timeout to 20 minutes
  testing/testing.h
Labels: build

#2778 Build: Fix version bumping
  deploy/get_new_version.py
Labels: bug, build
