Repository MDSplus/mdsplus, pull requests merged in 2024-03, with the labels that each got.

#2723 Fix: "set current" now works with thick-client
  treeshr/RemoteAccess.c
Labels: bug, US Priority, tool/tcl, branch/alpha, core

#2728 Fix: remove nix package text so matches alpha README.md
  README.md
Labels: documentation

#2727 Build: Add 'Release' as a commit prefix
  deploy/get_new_version.py
Labels: build
