Repository MDSplus/mdsplus, pull requests merged in 2025-03, with the labels that each got.

#2861 Fix: C++ TreeNode remove unnecessary Tree duplication
  mdsobjects/cpp/mdstreeobjects.cpp
Labels: bug, api/cpp

#2862 Fix: Cleanup PR#2861
  mdsobjects/cpp/mdstreeobjects.cpp
Labels: api/cpp

#2860 Fix: the find_fun() function now checks the status variable
  tdishr/TdiVar.c
Labels: bug, core

#2865 Fix: Apple Silicon - add a define
  configure.ac
Labels: bug, US Priority, core

#2864 Fix: delete references to deprecated data types
  tdic/TdiShrExt.c
Labels: bug, core

#2867 Fix: Apple Silicon - defines for use with LibCallgFfi()
  include/libroutines.h
Labels: bug, US Priority, core

#2869 Fix: Apple Silicon -- traverser now calls TDI functions directly
  xmdsshr/XmdsExpr.c
Labels: bug, US Priority, tool/traverser, os/mac

#2868 Fix: add missing va_end() statements
  mdslib/MdsLib.c
  mdsobjects/cpp/mdsdataobjects.cpp
  mdsshr/MDSprintf.c
  mdsshr/mdsmsg.c
  roam/roam_gridmap_callout.c
  servershr/ServerSendMessage.c
  tdic/TdiShrExt.c
Labels: bug, core

#2872 Revert "Fix: Apple Silicon -- traverser now calls TDI functions directly (#2869)"
  xmdsshr/XmdsExpr.c
Labels: bug, US Priority, tool/traverser, os/mac, core

#2873 Revert "Fix: Apple Silicon - defines for use with LibCallgFfi() (#2867)"
  include/libroutines.h
Labels: bug, US Priority, os/mac, core

#2874 Fix: Apple Silicon - eliminate traverser segfault associated with TDI intrinsic functions
  xmdsshr/XmdsExpr.c
Labels: bug, US Priority, tool/traverser, os/mac

#2870 Fix: IDL tests now have correct paths
  idl/testing/run_tests.py
Labels: bug, test, api/idl

#2876 Fix: in mdsconnect.pro, add a test for darwin which is what IDL returns for MacOS
  idl/mdsconnect.pro
Labels: bug, US Priority, api/idl

#2878 Fix: Apple Silicon - specify default for PyLib for MacOS
  tdishr/TdiExtPython.c
Labels: bug, US Priority, os/mac, core

#2879 Fix: correct some paths in the MATLAB tests
  matlab/testing/run_tests.py
Labels: bug, test, api/matlab

#2866 Feature: Enable optional args in python wrapper createPulse
  python/MDSplus/tree.py
Labels: feature, api/python

#2881 Fix: errors with asan and tsan
  mdstcpip/io_routines/IoRoutinesThread.c
  treeshr/TreeOpen.c
Labels: bug, core

#2889 Fix: remote_submit_helper.fun now accepts zero id and has a timeout
  tdi/remote/MdsConnect.fun
  tdi/remote/remote_submit_helper.fun
Labels: bug, US Priority, tool/mdsip, tool/tdi, core
