Repository MDSplus/mdsplus, pull requests merged in 2025-04, with the labels that each got.

#2892 Fix: LibCallg() now has similar edits to LibCallgFfi()
  mdsshr/librtl.c
Labels: bug, core

#2893 Fix: ensure SsINTERNAL not treated as OK status
  mdstcpip/mdsipshr/ConnectToMds.c
  mdstcpip/mdsipshr/Connections.c
  mdstcpip/mdsipshr/DoMessage.c
  mdstcpip/mdsipshr/GetAnswerInfo.c
  mdstcpip/mdsipshr/GetMdsMsg.c
  mdstcpip/mdsipshr/SendArg.c
  tdishr/TdiEvaluate.c
Labels: bug, core

#2894 Fix: mdsip_server no longer uses broken compression level
  mdstcpip/mdsip_server
Labels: bug, tool/mdsip

#2895 Fix: delete extra arg to GetAnswerInfoTS()
  servershr/ServerGetInfo.c
Labels: bug, core

#2832 Fix: treatment of scalars in TdiTrans.c
  include/mdsdescrip.h
  tdishr/TdiTrans.c
  tditest/testing/test-tdishr.ans
  tditest/testing/test-tdishr.tdi
Labels: bug, tool/tdi
